spring.application.name=pizza-app
#spring.security.user.name=user
#spring.security.user.password=password
# Show SQL in console (helps you see what's happening)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

# H2 console (to see database directly in browser)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:pizzadb